### PR TITLE
被动采集功能重构&若干问题修复

### LINKED ISSUE #29: TopGauge prevent NoopId
### Describe the bug

A Noop MetricId will cause metric type cast err.

### Actual behavior

ignore noopId, do not register it .

### Environment

- SOFALookout version: 1.4.*
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): -
- Maven version: 3.2.5
- IDE version: -

### PR DESCRIPTION
**Pull request by luyiisme**
- fix #29 TopGauge prevent NoopId
- fix gaugeWrapper&InfoWrapper resettable；
- add linux os metrics export
- merge two registries (lookoutRegistry and ResettableStepRegistry)
- add access control for reacitve mode;

### CODE REVIEW

File: client/lookout-reg-server/src/main/java/com/alipay/lookout/remote/step/ResettableStepRegistry.java [hunk 1]
```diff
@@ -14,39 +14,40 @@
...
 
 /**
- * 可调整 step 的 Registry
+ * 可调整 step 的 Registry reactive mode;
  *
  * @author xiangfeng.xzc
  * @date 2018/7/26
  */
-public class ResettableStepRegistry extends StepRegistry implements ResettableStep,
-                                                        CommonTagsAccessor {
```
Comment (xzchaoo) [inline client/lookout-reg-server/src/main/java/com/alipay/lookout/remote/step/ResettableStepRegistry.java]: 重复实现CommonTagsAccessor接口

File: client/lookout-reg-server/src/main/java/com/alipay/lookout/remote/step/StepRegistry.java [hunk 2]
```diff
@@ -74,10 +75,12 @@ protected DistributionSummary newDistributionSummary(Id id) {
...
 
     protected long getStepMillis(Id id) {
-        if (fixedStepMillis > 0) {
-            return fixedStepMillis;
+        if (proactive) {
+            return getLookoutConfig().stepMillis(PriorityTagUtil.resolve(id.tags()));
         }
-        return getLookoutConfig().stepMillis(PriorityTagUtil.resolve(id.tags()));
+        //reactive mode
+        Preconditions.checkState(currentStepMillis > 0);
```
Comment (xzchaoo) [inline client/lookout-reg-server/src/main/java/com/alipay/lookout/remote/step/StepRegistry.java]: currentStepMillis 可能为负数, 此时认为是poller停止

File: client/lookout-reg-server/src/main/java/com/alipay/lookout/remote/report/poller/PollerController.java [hunk 3]
```diff
@@ -18,44 +18,35 @@
...
-import java.util.concurrent.ThreadPoolExecutor;
-import java.util.concurrent.TimeUnit;
+import java.util.*;
+import java.util.concurrent.*;
 
 /**
  * @author xiangfeng.xzc
  * @date 2018/7/26
  */
 public class PollerController implements Closeable {
```
Comment (xzchaoo) [inline client/lookout-reg-server/src/main/java/com/alipay/lookout/remote/report/poller/PollerController.java]: public synchronized void update(long newStep, int newSlotCount) {
        // step <=0 认为是停止, 需要先 triggerIdle 否则一段时间内, step<=0 且处于reactive状态.
        if (active && newStep <= 0) {
            triggerIdle();
        }
        setSlotCount(newSlotCount);
        setStep(newStep);
        registry.setStep(newStep);
    }
